context:
  version: "2.2.21"

package:
  name: fastcore
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/fastcore/fastcore-${{ version }}.tar.gz
  sha256: 5687cc537a7aba8b88e43264e666ad8cc3f8e376d1b9c27f4d6ba6a4e098ac0a

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - py2pyi=fastcore.py2pyi:py2pyi
      - replace_wildcards=fastcore.py2pyi:replace_wildcards

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=64
    - pip
  run:
    - python >=${{ python_min }}
tests:
  - python:
      imports:
        - fastcore
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      - py2pyi --help
      - replace_wildcards --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  summary: Python supercharged for fastai development
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/fastai/fastcore

extra:
  recipe-maintainers:
    - kai-tub
    - synapticarbors
    - thewchan
